/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as WelcomeIndexRouteImport } from './routes/welcome/index'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as WelcomeModeRouteImport } from './routes/welcome/mode'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellHelpRouteImport } from './routes/_shell.help'
import { Route as ShellDevRouteImport } from './routes/_shell.dev'
import { Route as ShellAboutRouteImport } from './routes/_shell.about'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeIndexRoute = WelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const WelcomeModeRoute = WelcomeModeRouteImport.update({
  id: '/welcome/mode',
  path: '/welcome/mode',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHelpRoute = ShellHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDevRoute = ShellDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAboutRoute = ShellAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/about': typeof ShellAboutRoute
  '/dev': typeof ShellDevRoute
  '/help': typeof ShellHelpRoute
  '/settings': typeof ShellSettingsRoute
  '/welcome/mode': typeof WelcomeModeRoute
  '/welcome/': typeof WelcomeIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof ShellAboutRoute
  '/dev': typeof ShellDevRoute
  '/help': typeof ShellHelpRoute
  '/settings': typeof ShellSettingsRoute
  '/welcome/mode': typeof WelcomeModeRoute
  '/': typeof ShellIndexRoute
  '/welcome': typeof WelcomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/about': typeof ShellAboutRoute
  '/_shell/dev': typeof ShellDevRoute
  '/_shell/help': typeof ShellHelpRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/welcome/mode': typeof WelcomeModeRoute
  '/_shell/': typeof ShellIndexRoute
  '/welcome/': typeof WelcomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dev'
    | '/help'
    | '/settings'
    | '/welcome/mode'
    | '/welcome/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/dev'
    | '/help'
    | '/settings'
    | '/welcome/mode'
    | '/'
    | '/welcome'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/about'
    | '/_shell/dev'
    | '/_shell/help'
    | '/_shell/settings'
    | '/welcome/mode'
    | '/_shell/'
    | '/welcome/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  WelcomeModeRoute: typeof WelcomeModeRoute
  WelcomeIndexRoute: typeof WelcomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/': {
      id: '/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof WelcomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/welcome/mode': {
      id: '/welcome/mode'
      path: '/welcome/mode'
      fullPath: '/welcome/mode'
      preLoaderRoute: typeof WelcomeModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/help': {
      id: '/_shell/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ShellHelpRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dev': {
      id: '/_shell/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof ShellDevRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/about': {
      id: '/_shell/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ShellAboutRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAboutRoute: typeof ShellAboutRoute
  ShellDevRoute: typeof ShellDevRoute
  ShellHelpRoute: typeof ShellHelpRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAboutRoute: ShellAboutRoute,
  ShellDevRoute: ShellDevRoute,
  ShellHelpRoute: ShellHelpRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  WelcomeModeRoute: WelcomeModeRoute,
  WelcomeIndexRoute: WelcomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
